import { Inter } from 'next/font/google'
import { Header } from '@/app/components/Header'
import './globals.css'
import { Footer } from '@/app/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: ' Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) =>{
  return (
    <html lang="en">      
      <body className={inter.className}>
          <Header/>
           <main>
             {children}
           </main>
           <Footer/>
      </body>
    </html>
  )
}

export default  RootLayout;