import { Inter } from 'next/font/google'
import { Header } from '@/app/components/Header'
import './globals.css'
import { Footer } from '@/app/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: ' Next App',
  description: 'Generated by create next app',
  
}

const RootLayout = ({ children }) =>{
  return (
    <html lang="en">   
       <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          rel="stylesheet"
          href={`https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap`}
        />
      </head>   
      <body className={inter.className}>
          <Header/>
           <main>
             {children}
           </main>
           <Footer/>
      </body>
    </html>
  )
}

export default  RootLayout;